# Generated by Django 2.2.3 on 2019-12-22 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191223_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 1, 33, 41, 209532), verbose_name='date published'),
        ),
    ]
