# Generated by Django 2.2.3 on 2019-12-23 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191223_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 23, 45, 2, 700397), verbose_name='date published'),
        ),
    ]
